build/azDevOps/azure/air-infrastructure-data-vars.yml
build/azDevOps/azure/air-infrastructure-data.yml
deploy/azure/infra/constraints.tf
deploy/azure/infra/data.tf
deploy/azure/infra/main.tf
deploy/azure/infra/vars.tf

created Pipeline to provision Data Environment 
to have a standard Data Environment for stacks
using standard pipeline have added Terraform modules, which created KV, ADF, enabled the diagnostic setting in ADF, ADL and created linked services in ADF for KV, ADLS and blob
https://lucid.app/lucidchart/6a64a40a-c181-4696-b919-e0f22c34262a/edit?invitationId=inv_7ac84265-4713-4f55-ab42-c023fbeeba22&referringApp=slack&page=lThzo3Fv6uCT#
Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR.
Notes on how a reviewer can test the changes, e.g. how to run the tests.

feat: Data Enviroment provisioning 

---

build/azDevOps/azure/air-infrastructure-data-vars.yml
deploy/azure/infra/main.tf
deploy/azure/infra/vars.tf

Added  approach to add secrets to Azure KV

Feat: add secretes

---

build/azDevOps/azure/air-infrastructure-data-vars.yml
build/azDevOps/azure/air-infrastructure-data.yml
deploy/azure/infra/main.tf
deploy/azure/infra/vars.tf

Feat git integration

---

de_build/adf/adf-pipeline.yml

Fix pipeline

---

de_build/adf/adf-pipeline-vars.yml
de_build/adf/adf-pipeline.yml

Fix  cleanup vars

---

build/azDevOps/azure/air-infrastructure-data-vars.yml
build/azDevOps/azure/air-infrastructure-data.yml
deploy/azure/infra/main.tf
deploy/azure/infra/vars.tf

Feat add sql

---

data_factory/adf_managed/linkedService/ls_AzureSql_ExampleSource.json

Updating the secret used in the linked service for the example SQL Server.

Updating linkedService: ls_AzureSql_ExampleSource

---

ingest/ingest-config-pipeline.yml

Fixed trigger for ingest config pipeline

fixed config pipeline

---

de_build/job-pipeline-vars.yml
ingest/ingest-config-pipeline.yml

fixed Tag creation issue

---

data_processing/data-processing-config-pipeline.yml
de_build/job-pipeline-vars.yml
ingest/ingest-config-pipeline.yml

Updated agent for Release creation

Updated agent for Release creation

---

ingest/ingest-config-pipeline.yml

updated logic for fetching last tag

fixed last tag issue

---

data_processing/data-processing-config-pipeline.yml
data_processing/jobs/silver/silver.yml
pysparkle/pysparkle-pipeline.yml

updated processing pipelines

---

data_processing/data-processing-config-pipeline.yml
data_processing/jobs/silver/silver.yml
ingest/release-creation-test.yml
pysparkle/pysparkle-pipeline.yml

Fixed-multiple tags issue for  processing pipelines

fixed-mutiple tag issue for  processing pipeline

---

ingest/jobs/Ingest_AzureSql_Example/ingest-azuresql-example.yml

Fixed pipline sql pipeline for cleanup

fix: updated for pipeline

---

data_processing/jobs/silver/silver.yml
ingest/jobs/Ingest_AzureSql_Example/ingest-azuresql-example.yml

updated pipeline

---

build/azDevOps/azure/air-infrastructure-data-vars.yml
build/azDevOps/azure/air-infrastructure-data.yml
deploy/azure/infra/data.tf
deploy/azure/infra/main.tf
deploy/azure/infra/vars.tf
deploy/azure/networking/main.tf
deploy/azure/networking/vars.tf

Added different private dns zones for all service into hub network

updated for pvt dns

---

build/azDevOps/azure/air-infrastructure-data.yml
build/azDevOps/azure/network/air-infrastructure-data-network.yml
deploy/azure/infra/data.tf
deploy/azure/infra/dns-link.tf
deploy/azure/infra/main.tf
deploy/azure/infra/vars.tf
deploy/azure/networking/main.tf
deploy/azure/networking/vars.tf

Fix enable dnslinkage

---

docs/workloads/azure/data/components/etl_pipelines/ingest_data_azure.md
docs/workloads/azure/data/intro_data_azure.md

Documentation updates following ADF refactor

Documentation updates

---

de_workloads/ingest/Ingest_AzureSql_Example/data_factory/adf_datasets.tf

Ensure linked service is deployed before dataset.

Fix - ADF add linked service dependency to dataset

---

pysparkle/pysparkle-pipeline.yml

Added fix for taskctl unkown command

Fix  taskctl unkown command

---

docs/workloads/azure/data/architecture/repository_data_azure.md
docs/workloads/azure/data/etl_pipelines/data_quality_azure.md
docs/workloads/azure/data/etl_pipelines/datastacks.md
docs/workloads/azure/data/etl_pipelines/etl_intro_data_azure.md
docs/workloads/azure/data/etl_pipelines/ingest_data_azure.md
docs/workloads/azure/data/etl_pipelines/pysparkle/pysparkle_quickstart.md
docs/workloads/azure/data/etl_pipelines/silver_data_azure.md
docs/workloads/azure/data/getting_started/etl_pipelines_deployment_azure.md
docs/workloads/azure/data/getting_started/getting_started.md
docs/workloads/azure/data/getting_started/shared_resources_deployment_azure.md
docs/workloads/azure/data/infrastructure_data_azure.md
docs/workloads/azure/data/intro_data_azure.md

Various fixes to links in documentation

Docs links fixes

---

docs/workloads/azure/data/getting_started/generate_project.md

[Fix: scaffold example URL]
Fix URL to scaffold example file.
Update reference to main branch.
Updated markdown
Updated markdown
Test new link

Fix: scaffold example URL

---

build/common-vars-template.yml

missing dot for template variable
stack-cli fails to generate project and replace values

missing dot for template variable

---

build/taskctl/tasks.yaml

[XXXX-<Title> - Please use the Work Item number and Title as PR Name, not subtasks]
A fix for bug [Bug 6970](https://amido-dev.visualstudio.com/Amido-Stacks/_workitems/edit/6970) 
this needed to fix the deployment pipeline for shared resources 
added out null on taskctl plan task 
Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR
Notes for QA

6970 - bugfix/Shared Resources: Pipeline template error

---

docs/workloads/azure/data/etl_pipelines/datastacks.md
docs/workloads/azure/data/getting_started/getting_started.md

Fix broken links in documentation.

fix broken links

---

docs/workloads/azure/data/requirements_data_azure.md

Added github token details on what it is and why its needed
Within this the UsePythonVersion in data would fail 
Updated requirements_data_azure.md and ran lint locally.

bug 6995 - added documentation for github token

---

deploy/azure/infra/main.tf
deploy/azure/networking/main.tf

update terraform module references to ensono

update terraform module references to ensono

---

de_workloads/processing/silver_movies_example_with_data_quality/config/data_quality/data_quality_config.json

Fix the paths in the DQ config in the silver example workload.
The DQ process was not reading from and writing to the correct locations.
Update values in config file.
Update values in config file.
Run silver example pipeline (with DQ) in ADF, verify it succeeds and the data is output in the staging container under the `movies` path.

update dq paths

---

datastacks/datastacks/azure/adls.py

Fix logic in `all_files_present_in_adls`.
As per the bug ticket, this was sometimes giving false negatives due to pagination.
Update to logic so it rechecks the paths for each file.
E2E tests run successfully with this logic updated.
Run unit tests & e2e tests.

7100 - Fix ADLS file check

---

README.md
datastacks/README.md

Fix links to website in README files.

Fix website links

---

docs/workloads/azure/data/data_engineering/data_quality_azure.md

Added documentation around outputting the DQ validation results as delta tables
Documentation
Docs
n/a
n/a

6364 - Results Table Documentation

---

build/taskctl/tasks.yaml

[XXXX-<Title> - Please use the Work Item number and Title as PR Name, not subtasks]
To fix the interpolation issue using the replace function, now means we don't get realtime feedback of terraform apply command
as there is bug in the AIR where its doesn't work if there is {{ 
added a workaround 
Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR
Notes for QA

fix: terraform plan out put

---

docs/workloads/azure/data/getting_started/fabric_deployment_guide.md

Update heading numbering in Fabric documentation page.

Fix 7125: Fabric docs numbering

---

docs/workloads/azure/data/getting_started/example_data_source.md

Update docs with addtional notes on how to access the SQL database that is deployed.
It was not clear that an admin password is auto generated for the database and added to key vault. Add some further documentation to make this clearer.
Docs updated.
Docs updated.
Review docs.

notes on accessing sql db

---

de_workloads/processing/gold_movies_example/data_factory/pipelines/arm_template.json

fix: add output path to gold example

fix: add output path to gold example

---

docs/workloads/azure/data/getting_started/ingest_pipeline_deployment_azure.md
docs/workloads/azure/data/getting_started/processing_pipeline_deployment_azure.md

[XXXX-<Title> - Please use the Work Item number and Title as PR Name, not subtasks]
A description of the change.
Why it's needed, background context.
More in-depth discussion of the change or implementation.
Screenshots / external resources / links / etc.
Link to documentation updated with changes impacted in the PR
Notes for QA

update examples in the docs

---

de_workloads/processing/gold_movies_example/de-process-ado-pipeline.yml
de_workloads/processing/silver_movies_example/de-process-ado-pipeline.yml

Update the respositoryName value in processing pipeline templates.
The fix issue creating github releases (bug 7140)
Update pipeline yaml in example pipelines
Yaml updated.
Ensure the example pipelines work as expected.

Fix 7140: Github release issue

---

docs/workloads/azure/data/getting_started/fabric_deployment_guide.md

Update to data docs for Fabric now it is in general availability.
Update docs.
Update docs.
Update docs.
npm run lint, test on local server.

Fabric documentation updates

---

docs/workloads/azure/data/getting_started/requirements_data_azure.md

Docs update.
To clarify that developing in a unix-based environment is recommended.
Docs update
Docs update
n/a

Update WSL note

---

docs/workloads/azure/data/getting_started/core_data_platform_deployment_azure.md

Docs update - remove option to deploy without private networking, as this is not available yet.
Docs update.
Docs update.
Docs update.
Docs update.

Remove private network false option
